server:
  address: 127.0.0.1
  port: 8080

spring:
  liquibase:
    enabled: false # manual
    change-log: classpath:changelog.xml

  mail:
    host: "smtp.sendgrid.net"
    port: 465
    protocol: "smtp"
    username: "apikey"
    password: "" # EXTERNAL
    properties:
      mail:
        smtp:
          socketFactory:
            class: "javax.net.ssl.SSLSocketFactory"

  main:
    web-application-type: NONE

#logging:
#  level:
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

liquibase:
  # TODO change the value below to true to enable liquibase
  manual: false

logRestRequestWebInterceptor:
  enabled: true

s3:
  enabled: false
  bucket: "" # EXTERNAL
  accessKey: "" # EXTERNAL
  secretKey: "" # EXTERNAL
  region: us-west-1
  endpoint: https://s3.us-west-1.wasabisys.com

elk:
  host: elk.cmlteam.com
  port: 10443
  application: file_storage_checker